/**
 * Home page only — capability tiles with technology slugs (must match `technologiesData` + `TechnologyLogo`).
 * Order is fixed per product spec.
 */
export const HOME_SERVICES_SHOWCASE = [
  {
    id: 'cms-ecommerce',
    title: 'CMS & E-commerce',
    tag: 'Platforms',
    shortDescription:
      'Storefronts, content systems, and commerce stacks — from Shopify and WordPress to headless builds.',
    bg: '#EBD9C4',
    accent: '#A07830',
    techSlugs: [
      'shopify',
      'woocommerce',
      'wordpress',
      'magento',
      'bigcommerce',
      'prestashop',
      'opencart',
      'nopcommerce',
      'joomla',
      'wix',
      'webflow',
      'squarespace',
      'elementor',
      'wpbakery',
      'brizy',
    ],
  },
  {
    id: 'frontend-development',
    title: 'Frontend Development',
    tag: 'Engineering',
    shortDescription: 'Modern component architectures, performance-first SPAs, and polished product UI.',
    bg: '#C8E4F4',
    accent: '#3B82C4',
    techSlugs: ['reactjs', 'nextjs', 'vuejs', 'nuxtjs', 'vite', 'angular', 'html-bootstrap'],
  },
  {
    id: 'backend-development',
    title: 'Backend Development',
    tag: 'Engineering',
    shortDescription: 'APIs, services, and data layers engineered for scale, security, and clarity.',
    bg: '#C8EBE0',
    accent: '#1E8A6E',
    techSlugs: ['typo3', 'nodejs', 'nestjs', 'php', 'dotnet-core', 'python-django', 'graphql'],
  },
  {
    id: 'native-development',
    title: 'Native Development',
    tag: 'Mobile',
    shortDescription: 'Platform-native apps with tight OS integration and store-ready quality.',
    bg: '#D4E4F2',
    accent: '#2E6E9E',
    techSlugs: ['ios', 'android', 'swift', 'kotlin', 'java', 'objective-c'],
  },
  {
    id: 'cross-platform-development',
    title: 'Cross-Platform Development',
    tag: 'Mobile',
    shortDescription: 'One codebase, multiple stores — fast iteration without sacrificing reach.',
    bg: '#E2DCF5',
    accent: '#6B52A8',
    techSlugs: ['react-native', 'flutter', 'ionic'],
  },
  {
    id: 'devops',
    title: 'DevOps',
    tag: 'Infrastructure',
    shortDescription: 'Cloud, containers, and delivery pipelines that make releases boring (in a good way).',
    bg: '#C5E8E0',
    accent: '#1E8A6E',
    techSlugs: [
      'aws',
      'digitalocean',
      'gcp',
      'docker',
      'linux',
      'ssl-tls',
      'amazon-rds',
      'amazon-ec2',
      'amazon-ses',
      'aws-amplify',
    ],
  },
  {
    id: 'ui-ux-design',
    title: 'UI/UX Design',
    tag: 'Design',
    shortDescription: 'Research-led UX, systems thinking, and interfaces that feel intentional.',
    bg: '#E8E0F5',
    accent: '#6B52A8',
    techSlugs: [
      'figma',
      'adobe-xd',
      'sketch',
      'photoshop',
      'canva',
      'adobe-illustrator',
      'adobe-creative-cloud',
    ],
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    tag: 'Growth',
    shortDescription: 'Paid, organic, and lifecycle campaigns measured against real business outcomes.',
    bg: '#F3DDD0',
    accent: '#C96A2E',
    techSlugs: [
      'google-ads',
      'seo',
      'facebook-ads',
      'linkedin-ads',
      'youtube-ads',
      'pinterest-ads',
      'mailchimp',
      'snapchat-ads',
      'instagram-ads',
      'x',
    ],
  },
  {
    id: 'database',
    title: 'Database',
    tag: 'Data',
    shortDescription: 'Relational, document, cache, and managed data layers chosen for your workload.',
    bg: '#C9EBE6',
    accent: '#0D9488',
    techSlugs: ['mongodb', 'supabase', 'mysql', 'postgresql', 'firebase', 'prisma', 'redis'],
  },
  {
    id: 'ai-machine-learning',
    title: 'AI & Machine Learning',
    tag: 'Intelligence',
    shortDescription:
      'LLMs, generative AI, intelligent automation, and modern AI-assisted engineering workflows for production-grade products.',
    bg: '#E4E8FC',
    accent: '#4F46E5',
    techSlugs: [
      'vibe-coding',
      'openai',
      'google-gemini',
      'generative-ai',
      'claude',
      'n8n',
      'make',
      'ai-bot',
    ],
  },
];
