export const TECHNOLOGIES = [
  // Frontend
  {
    slug: 'reactjs',
    name: 'React.js',
    category: 'frontend',
    accent: '#61DAFB',
    summary: 'Component-driven UI library for fast, interactive web apps.',
    overview:
      'React is a component-based UI library that excels at building interactive product experiences. It’s a strong fit for dashboards, SaaS applications, and any interface that benefits from reusable components and predictable state management.',
    keyBenefits: ['Reusable components', 'Huge ecosystem', 'Great performance patterns', 'Excellent DX & tooling'],
    useCases: ['SaaS products', 'Admin dashboards', 'Design-system driven apps', 'Marketing sites with interactive sections'],
    whyChoose: [
      'We build scalable component architectures and design systems.',
      'We optimize rendering, bundles, and loading behavior for speed.',
      'We ship accessible UI with consistent interaction patterns.',
    ],
    related: ['nextjs', 'typescript', 'graphql', 'vite'],
  },
  {
    slug: 'nextjs',
    name: 'Next.js',
    category: 'frontend',
    accent: '#111111',
    summary: 'Production React framework for SSR, routing, and performance.',
    overview:
      'Next.js is a full-stack React framework that enables fast routing, server rendering, and performance primitives. It’s ideal when you need SEO-friendly pages, strong performance, and a structured production setup.',
    keyBenefits: ['SEO-ready rendering', 'File-based routing', 'Performance primitives', 'Flexible deployment options'],
    useCases: ['Content-heavy sites', 'Hybrid apps (SSR + SPA)', 'Landing pages & SEO', 'Enterprise portals'],
    whyChoose: [
      'We choose the right rendering strategy per page (SSR/SSG/CSR).',
      'We implement caching and data-fetching patterns cleanly.',
      'We keep builds fast and bundles lean as the app grows.',
    ],
    related: ['reactjs', 'typescript', 'graphql', 'vite'],
  },
  {
    slug: 'vuejs',
    name: 'Vue.js',
    category: 'frontend',
    accent: '#42B883',
    summary: 'Progressive framework for building approachable, performant UIs.',
    overview:
      'Vue is a progressive framework that’s approachable and flexible, with a strong component model and excellent performance. It’s a great choice for teams that want speed of development without sacrificing quality.',
    keyBenefits: ['Fast iteration', 'Clean component model', 'Strong performance', 'Great learning curve'],
    useCases: ['Product UIs', 'Internal tools', 'SPA experiences', 'Widget-style embeds'],
    whyChoose: [
      'We architect reusable components and consistent state flows.',
      'We integrate Vue with APIs and auth securely.',
      'We optimize loading and runtime behavior for real users.',
    ],
    related: ['nuxtjs', 'typescript', 'graphql', 'vite'],
  },
  {
    slug: 'nuxtjs',
    name: 'Nuxt.js',
    category: 'frontend',
    accent: '#00DC82',
    summary: 'Vue framework for SSR, routing, and modern DX.',
    overview:
      'Nuxt brings structure and production-ready defaults to Vue projects, including routing and server rendering options. It’s a strong fit for SEO requirements and content-driven product experiences.',
    keyBenefits: ['SSR/SSG options', 'Convention-based structure', 'Great DX', 'SEO-friendly'],
    useCases: ['SEO pages', 'Content sites', 'Hybrid product experiences', 'Marketing + app blends'],
    whyChoose: [
      'We pick the right rendering mode per route for speed and SEO.',
      'We keep data flows predictable and maintainable.',
      'We ensure accessibility and consistent design system usage.',
    ],
    related: ['vuejs', 'typescript', 'graphql', 'vite'],
  },
  {
    slug: 'vite',
    name: 'Vite',
    category: 'frontend',
    accent: '#646CFF',
    summary: 'Lightning-fast dev server and build tool for modern web projects.',
    overview:
      'Vite is a modern build tool that provides a very fast development experience and efficient production builds. It’s ideal for teams that value iteration speed and clean tooling.',
    keyBenefits: ['Fast dev server', 'Modern bundling', 'Great plugin ecosystem', 'Simple configuration'],
    useCases: ['React/Vue apps', 'Component libraries', 'Admin dashboards', 'Marketing sites'],
    whyChoose: [
      'We keep tooling simple and stable across environments.',
      'We optimize production bundles and asset delivery.',
      'We standardize build pipelines for predictable releases.',
    ],
    related: ['reactjs', 'vuejs', 'typescript', 'graphql'],
  },
  {
    slug: 'angular',
    name: 'Angular',
    category: 'frontend',
    accent: '#DD0031',
    summary: 'Enterprise-ready framework for large, structured web apps.',
    overview:
      'Angular is a full-featured framework designed for large applications that benefit from structure and conventions. It’s a reliable choice for enterprise teams that need consistency at scale.',
    keyBenefits: ['Strong structure', 'TypeScript-first', 'Tooling included', 'Scales well for large teams'],
    useCases: ['Enterprise portals', 'Complex internal tools', 'Long-lived products', 'Role-heavy apps'],
    whyChoose: [
      'We keep architecture modular to avoid monolith frontends.',
      'We implement forms, validation, and state patterns cleanly.',
      'We focus on maintainability and performance over time.',
    ],
    related: ['typescript', 'nodejs', 'graphql', 'vite'],
  },
  {
    slug: 'html-bootstrap',
    name: 'HTML / Bootstrap',
    category: 'frontend',
    accent: '#7952B3',
    summary: 'Semantic HTML with rapid UI scaffolding via Bootstrap.',
    overview:
      'For fast delivery, semantic HTML paired with Bootstrap can produce clean, responsive layouts quickly. It’s useful for MVPs, marketing pages, and admin areas where speed matters.',
    keyBenefits: ['Fast UI scaffolding', 'Responsive grid system', 'Consistent components', 'Widely supported'],
    useCases: ['Landing pages', 'Admin panels', 'MVP interfaces', 'Documentation sites'],
    whyChoose: [
      'We keep markup semantic and accessible.',
      'We customize Bootstrap thoughtfully (not generic templates).',
      'We ensure performance and clean CSS output.',
    ],
    related: ['vite', 'reactjs', 'vuejs', 'typescript'],
  },

  // Backend
  {
    slug: 'typo3',
    name: 'TYPO3',
    category: 'backend',
    accent: '#FF8700',
    summary: 'Enterprise CMS built for structured content, governance, and complex editorial workflows.',
    overview:
      'TYPO3 is an enterprise-grade content management system known for flexibility, governance, and multilingual, multi-site publishing. It’s a strong fit when content structure, permissions, and editorial workflows matter as much as design.',
    keyBenefits: ['Strong permissions & governance', 'Multisite & multilingual support', 'Structured content modeling', 'Enterprise extensibility'],
    useCases: ['Enterprise websites', 'Multi-brand platforms', 'Government/education portals', 'Content-heavy experiences'],
    whyChoose: [
      'We model content types for scalability and clean editorial experience.',
      'We implement secure permissions and publishing workflows.',
      'We optimize performance, caching, and maintainability for long-lived sites.',
    ],
    related: ['php', 'graphql', 'nextjs', 'nodejs'],
  },
  {
    slug: 'typescript',
    name: 'TypeScript',
    category: 'backend',
    accent: '#3178C6',
    summary: 'Typed JavaScript that improves quality, maintainability, and tooling.',
    overview:
      'TypeScript adds types to JavaScript, improving reliability and clarity in larger codebases. It’s especially valuable for APIs and services where correctness and refactoring safety matter.',
    keyBenefits: ['Safer refactors', 'Better IDE tooling', 'Clear contracts', 'Fewer runtime bugs'],
    useCases: ['API services', 'Monorepos', 'Shared types across frontend/backend', 'SDK development'],
    whyChoose: [
      'We design types as product contracts (not just annotations).',
      'We keep builds fast while maintaining strictness where it counts.',
      'We align runtime validation with types for safety.',
    ],
    related: ['nodejs', 'nestjs', 'graphql', 'reactjs'],
  },
  {
    slug: 'nodejs',
    name: 'Node.js',
    category: 'backend',
    accent: '#3C873A',
    summary: 'Fast server-side runtime ideal for APIs, realtime, and tooling.',
    overview:
      'Node.js is a great choice for modern APIs and realtime systems. It pairs well with TypeScript and supports rapid delivery without sacrificing scalability when engineered well.',
    keyBenefits: ['Fast iteration', 'Excellent ecosystem', 'Realtime-friendly', 'TypeScript pairing'],
    useCases: ['REST/GraphQL APIs', 'Realtime apps', 'Integrations', 'Background jobs'],
    whyChoose: [
      'We build clean service boundaries and predictable architecture.',
      'We optimize performance with caching and efficient IO patterns.',
      'We secure APIs with best-practice auth and validation.',
    ],
    related: ['typescript', 'nestjs', 'graphql', 'vite'],
  },
  {
    slug: 'nestjs',
    name: 'Nest.js',
    category: 'backend',
    accent: '#E0234E',
    summary: 'Opinionated Node framework for scalable server applications.',
    overview:
      'Nest.js brings structure to Node backend development with a modular architecture and strong conventions. It’s ideal for larger teams and complex domains that benefit from clear patterns.',
    keyBenefits: ['Modular architecture', 'TypeScript-first', 'Great testing story', 'Enterprise patterns'],
    useCases: ['Large APIs', 'Multi-module services', 'BFF layers', 'Complex domain systems'],
    whyChoose: [
      'We keep modules cohesive and boundaries clear.',
      'We implement clean validation, auth, and observability.',
      'We ensure testability across services and modules.',
    ],
    related: ['nodejs', 'typescript', 'graphql', 'dotnet-core'],
  },
  {
    slug: 'php',
    name: 'PHP / Laravel',
    category: 'backend',
    accent: '#777BB4',
    summary: 'Battle-tested backend stack for fast product delivery.',
    overview:
      'Laravel offers a productive framework for building robust backends quickly. It’s a solid choice for business applications, admin systems, and products that need speed with proven conventions.',
    keyBenefits: ['Rapid development', 'Strong conventions', 'Mature ecosystem', 'Great developer productivity'],
    useCases: ['Business apps', 'CMS backends', 'Admin systems', 'APIs and integrations'],
    whyChoose: [
      'We keep code organized with clean domain boundaries.',
      'We prioritize security (auth, validation, data access).',
      'We optimize performance and database patterns for scale.',
    ],
    related: ['graphql', 'nodejs', 'typescript', 'python-django'],
  },
  {
    slug: 'dotnet-core',
    name: '.NET Core',
    category: 'backend',
    accent: '#512BD4',
    summary: 'High-performance backend runtime for enterprise-grade systems.',
    overview:
      '.NET Core is a high-performance platform suited to enterprise services and complex domains. It’s a strong option when reliability, performance, and long-term support are priorities.',
    keyBenefits: ['High performance', 'Enterprise maturity', 'Strong typing', 'Great tooling'],
    useCases: ['Enterprise services', 'High-throughput APIs', 'Domain-heavy systems', 'Internal platforms'],
    whyChoose: [
      'We model complex domains cleanly and maintainably.',
      'We build observable services with robust error handling.',
      'We focus on performance without sacrificing clarity.',
    ],
    related: ['typescript', 'nodejs', 'graphql', 'nestjs'],
  },
  {
    slug: 'python-django',
    name: 'Python / Django',
    category: 'backend',
    accent: '#092E20',
    summary: 'Rapid development framework with a strong ecosystem.',
    overview:
      'Django helps teams ship backend systems quickly with strong defaults. It’s great for data-driven products, internal tools, and APIs that need fast iteration.',
    keyBenefits: ['Fast delivery', 'Strong defaults', 'Great admin tools', 'Rich ecosystem'],
    useCases: ['Data-driven products', 'Internal tools', 'APIs', 'Content-heavy platforms'],
    whyChoose: [
      'We structure apps for maintainability as features grow.',
      'We secure auth, permissions, and data access properly.',
      'We optimize queries and caching for production load.',
    ],
    related: ['graphql', 'nodejs', 'php', 'typescript'],
  },
  {
    slug: 'graphql',
    name: 'GraphQL',
    category: 'backend',
    accent: '#E10098',
    summary: 'Flexible API layer for modern product experiences.',
    overview:
      'GraphQL is an API layer that lets clients request exactly the data they need. It’s a strong fit for complex UIs, multi-client products, and systems where data needs vary across screens.',
    keyBenefits: ['Precise data fetching', 'Strong schema contracts', 'Great for complex UIs', 'Evolves without version sprawl'],
    useCases: ['Complex dashboards', 'Multi-client apps', 'BFF layers', 'Aggregated APIs'],
    whyChoose: [
      'We design schemas that model the product cleanly.',
      'We implement caching, auth, and query limits for safety.',
      'We keep resolvers performant with batching patterns.',
    ],
    related: ['typescript', 'nodejs', 'reactjs', 'nextjs'],
  },

  // Mobile — Native
  {
    slug: 'android',
    name: 'Android',
    category: 'mobile-native',
    accent: '#3DDC84',
    summary: 'Native Android development for fast, reliable experiences across devices.',
    overview:
      'Android native development enables deep platform integration, strong performance, and polished UX patterns. It’s ideal for apps that need device capabilities, strict performance targets, or platform-specific UI.',
    keyBenefits: ['Best-in-class performance', 'Deep device integration', 'Platform-native UX', 'Long-term maintainability'],
    useCases: ['Consumer apps', 'Fintech apps', 'IoT companions', 'Enterprise device fleets'],
    whyChoose: [
      'We build stable architectures with clear module boundaries.',
      'We optimize performance, startup time, and app size.',
      'We ship secure storage, auth, and API integrations.',
    ],
    related: ['kotlin', 'java', 'ios', 'flutter'],
  },
  {
    slug: 'ios',
    name: 'iOS',
    category: 'mobile-native',
    accent: '#111111',
    summary: 'Native iOS development with smooth interactions and premium polish.',
    overview:
      'Native iOS development delivers top-tier performance and a refined user experience. It’s the best choice when you need Apple ecosystem features, high UX expectations, and a strong foundation for long-lived products.',
    keyBenefits: ['Premium UX', 'Best performance', 'Apple ecosystem integration', 'Reliable release workflows'],
    useCases: ['Subscription apps', 'B2B companion apps', 'Health & fitness apps', 'Retail & loyalty apps'],
    whyChoose: [
      'We implement modern iOS architecture patterns for scale.',
      'We prioritize responsiveness, accessibility, and polish.',
      'We ship with analytics, crash reporting, and QA workflows.',
    ],
    related: ['swift', 'objective-c', 'android', 'react-native'],
  },
  {
    slug: 'swift',
    name: 'Swift',
    category: 'mobile-native',
    accent: '#F05138',
    summary: 'Modern language for fast, safe, and expressive iOS development.',
    overview:
      'Swift is Apple’s modern language for building iOS apps. It provides safety features, strong performance, and a developer-friendly experience for building reliable mobile products.',
    keyBenefits: ['Safe by design', 'Fast runtime', 'Modern language features', 'Great tooling'],
    useCases: ['iOS apps', 'Apple platform modules', 'Performance-critical features', 'Long-lived products'],
    whyChoose: [
      'We write maintainable Swift with clean layers and tests.',
      'We optimize performance and app startup behaviors.',
      'We integrate APIs and offline caching safely.',
    ],
    related: ['ios', 'objective-c', 'react-native', 'flutter'],
  },
  {
    slug: 'kotlin',
    name: 'Kotlin',
    category: 'mobile-native',
    accent: '#7F52FF',
    summary: 'Modern language for concise, safe Android development.',
    overview:
      'Kotlin is the modern standard for Android development. It improves safety and productivity while enabling great performance and interoperability with Java.',
    keyBenefits: ['Concise syntax', 'Null-safety', 'Interoperable with Java', 'Excellent Android tooling'],
    useCases: ['Android apps', 'Modular architectures', 'Enterprise apps', 'Performance-critical UI'],
    whyChoose: [
      'We build robust Android architectures with clean state flows.',
      'We ensure reliability with tests and crash monitoring.',
      'We optimize network, storage, and runtime performance.',
    ],
    related: ['android', 'java', 'flutter', 'ionic'],
  },
  {
    slug: 'java',
    name: 'Java',
    category: 'mobile-native',
    accent: '#E76F00',
    summary: 'Battle-tested language still used across Android and enterprise ecosystems.',
    overview:
      'Java remains common in Android and enterprise environments. It’s a reliable, mature language with extensive libraries and long-term support.',
    keyBenefits: ['Mature ecosystem', 'Strong tooling', 'Long-term support', 'Wide talent pool'],
    useCases: ['Legacy Android apps', 'Enterprise integrations', 'SDKs', 'Platform modules'],
    whyChoose: [
      'We modernize safely and reduce legacy risk over time.',
      'We keep builds stable and codebase maintainable.',
      'We implement performance and reliability improvements incrementally.',
    ],
    related: ['android', 'kotlin', 'nodejs', 'dotnet-core'],
  },
  {
    slug: 'objective-c',
    name: 'Objective-C',
    category: 'mobile-native',
    accent: '#6E6E6E',
    summary: 'Legacy iOS language for maintaining and extending existing applications.',
    overview:
      'Objective-C is still relevant for maintaining older iOS apps and libraries. We use it when extending legacy codebases or bridging to modern Swift safely.',
    keyBenefits: ['Maintains legacy apps', 'Interoperates with Swift', 'Stable ecosystem', 'Proven patterns'],
    useCases: ['Legacy iOS apps', 'Library maintenance', 'Incremental migration', 'Hybrid codebases'],
    whyChoose: [
      'We migrate safely to Swift without breaking releases.',
      'We reduce risk with incremental refactors.',
      'We keep performance and memory usage predictable.',
    ],
    related: ['ios', 'swift', 'react-native', 'flutter'],
  },

  // Mobile — Cross-platform
  {
    slug: 'react-native',
    name: 'React Native',
    category: 'mobile-cross-platform',
    accent: '#61DAFB',
    summary: 'Cross-platform mobile development with a React-based component model.',
    overview:
      'React Native enables shared development across iOS and Android while still delivering high-quality experiences. It’s ideal for teams that want speed and consistency across platforms.',
    keyBenefits: ['Shared codebase', 'Fast iteration', 'Strong ecosystem', 'Native capabilities when needed'],
    useCases: ['MVPs', 'Consumer apps', 'Internal tools', 'Cross-platform product suites'],
    whyChoose: [
      'We keep performance smooth with native-friendly patterns.',
      'We build reusable UI components and consistent navigation.',
      'We integrate native modules where required.',
    ],
    related: ['reactjs', 'ios', 'android', 'flutter'],
  },
  {
    slug: 'flutter',
    name: 'Flutter',
    category: 'mobile-cross-platform',
    accent: '#02569B',
    summary: 'Cross-platform framework for pixel-perfect UIs and high performance.',
    overview:
      'Flutter delivers consistent UI across platforms with excellent performance. It’s a strong choice when design fidelity and predictable UI rendering are top priorities.',
    keyBenefits: ['High performance', 'Pixel-perfect UI', 'Single codebase', 'Great tooling'],
    useCases: ['Consumer apps', 'Design-heavy products', 'Multi-platform apps', 'Rapid prototyping'],
    whyChoose: [
      'We build reusable widgets and scalable app architecture.',
      'We keep animations smooth and interactions consistent.',
      'We set up robust releases and QA workflows.',
    ],
    related: ['android', 'ios', 'react-native', 'kotlin'],
  },
  {
    slug: 'ionic',
    name: 'Ionic',
    category: 'mobile-cross-platform',
    accent: '#3880FF',
    summary: 'Hybrid app framework for shipping across platforms using web technologies.',
    overview:
      'Ionic is a pragmatic option for hybrid apps, especially when teams want to reuse web skills and ship quickly across platforms.',
    keyBenefits: ['Web-first skills', 'Fast delivery', 'Multi-platform reach', 'Good for internal apps'],
    useCases: ['Internal tools', 'Companion apps', 'MVPs', 'Content-driven apps'],
    whyChoose: [
      'We design for performance constraints of hybrid runtimes.',
      'We keep UI consistent and accessible.',
      'We integrate device capabilities safely.',
    ],
    related: ['reactjs', 'vite', 'android', 'ios'],
  },

  // Design tools
  {
    slug: 'figma',
    name: 'Figma',
    category: 'design',
    accent: '#F24E1E',
    summary: 'Collaborative design tool for UI, prototyping, and design systems.',
    overview:
      'Figma is a collaborative design platform used to build UI, prototypes, and design systems in one place. It’s ideal for teams that want fast iteration, shared libraries, and clean handoffs to engineering.',
    keyBenefits: ['Real-time collaboration', 'Design systems & libraries', 'Prototyping', 'Developer handoff'],
    useCases: ['Product UI design', 'Design systems', 'Prototypes & user testing', 'Handoff-ready specs'],
    whyChoose: [
      'We build scalable component libraries that match engineering constraints.',
      'We create interaction prototypes to validate flows early.',
      'We deliver handoff specs that reduce rework and ambiguity.',
    ],
    related: ['adobe-illustrator', 'photoshop', 'canva', 'adobe-creative-cloud'],
  },
  {
    slug: 'adobe-xd',
    name: 'Adobe XD',
    category: 'design',
    accent: '#FF61F6',
    summary: 'UI/UX design and prototyping tool for fast screen creation and flows.',
    overview:
      'Adobe XD supports rapid UI design and prototyping for product flows and interactive experiences. It’s useful for teams that want quick iteration across screens and prototype-driven feedback.',
    keyBenefits: ['Rapid screen design', 'Interactive prototyping', 'Design workflows', 'Sharing & review'],
    useCases: ['Wireframes', 'UI mockups', 'Prototypes', 'User flow validation'],
    whyChoose: [
      'We prototype quickly to de-risk complex journeys.',
      'We keep layouts consistent with reusable patterns.',
      'We translate prototypes into implementable UI specs.',
    ],
    related: ['figma', 'sketch', 'photoshop', 'adobe-creative-cloud'],
  },
  {
    slug: 'sketch',
    name: 'Sketch',
    category: 'design',
    accent: '#F7B500',
    summary: 'macOS design tool for UI screens, symbols, and component-based workflows.',
    overview:
      'Sketch is a macOS design tool widely used for UI layouts and component-based design. It’s effective for structured interface design and symbol-driven systems.',
    keyBenefits: ['Symbol-based components', 'Clean UI workflows', 'Plugins ecosystem', 'Reusable styles'],
    useCases: ['UI screen design', 'Component libraries', 'Design system foundations', 'Product mockups'],
    whyChoose: [
      'We structure symbols and libraries for consistent UI.',
      'We keep spacing and typography systems predictable.',
      'We deliver assets and specs ready for development.',
    ],
    related: ['figma', 'adobe-illustrator', 'photoshop', 'adobe-creative-cloud'],
  },
  {
    slug: 'photoshop',
    name: 'Photoshop',
    category: 'design',
    accent: '#31A8FF',
    summary: 'Industry-standard tool for image editing, compositing, and visual asset creation.',
    overview:
      'Photoshop is the standard for image editing and compositing. We use it to create high-quality visual assets, refine imagery, and produce marketing-ready graphics.',
    keyBenefits: ['Image editing', 'Compositing', 'Asset export', 'Retouching'],
    useCases: ['Marketing assets', 'UI imagery', 'Brand visuals', 'Photo retouching'],
    whyChoose: [
      'We deliver crisp, optimized assets for web and mobile.',
      'We maintain consistency across imagery and branding.',
      'We balance quality with performance constraints.',
    ],
    related: ['adobe-illustrator', 'adobe-creative-cloud', 'canva', 'figma'],
  },
  {
    slug: 'canva',
    name: 'Canva',
    category: 'design',
    accent: '#00C4CC',
    summary: 'Fast design tool for social, marketing, and brand-consistent templates.',
    overview:
      'Canva is a fast, template-driven design tool for marketing and brand assets. It’s ideal for teams that need quick iteration and consistent outputs across channels.',
    keyBenefits: ['Fast asset creation', 'Templates & brand kits', 'Team collaboration', 'Multi-format exports'],
    useCases: ['Social graphics', 'Pitch decks', 'Ads & banners', 'Brand templates'],
    whyChoose: [
      'We create reusable templates that stay on-brand.',
      'We ensure assets are export-ready and consistent.',
      'We streamline marketing production workflows.',
    ],
    related: ['figma', 'photoshop', 'adobe-creative-cloud', 'adobe-illustrator'],
  },
  {
    slug: 'adobe-illustrator',
    name: 'Adobe Illustrator',
    category: 'design',
    accent: '#FF9A00',
    summary: 'Vector design tool for icons, illustrations, and scalable brand assets.',
    overview:
      'Illustrator is the standard for vector design — logos, icons, and scalable brand assets. We use it for crisp visuals that stay sharp at any size.',
    keyBenefits: ['Scalable vectors', 'Iconography', 'Illustrations', 'Brand assets'],
    useCases: ['Icons', 'Logos', 'Illustrations', 'Brand systems'],
    whyChoose: [
      'We produce clean, scalable SVG assets.',
      'We keep icon styles consistent across products.',
      'We optimize vectors for web performance.',
    ],
    related: ['photoshop', 'figma', 'adobe-creative-cloud', 'canva'],
  },
  {
    slug: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    category: 'design',
    accent: '#DA1F26',
    summary: 'Creative suite for design, illustration, photo editing, and production workflows.',
    overview:
      'Adobe Creative Cloud is the ecosystem that powers professional design workflows. It enables teams to move from concept to production with consistent tooling and asset management.',
    keyBenefits: ['End-to-end suite', 'Professional workflows', 'Asset compatibility', 'Team-ready production'],
    useCases: ['Brand production', 'Marketing pipelines', 'Asset creation', 'Cross-tool collaboration'],
    whyChoose: [
      'We maintain consistent output quality across tools.',
      'We streamline asset exports and handoff formats.',
      'We keep files organized for team collaboration.',
    ],
    related: ['photoshop', 'adobe-illustrator', 'adobe-xd', 'figma'],
  },

  // DevOps / Cloud
  {
    slug: 'aws',
    name: 'Amazon Web Services (AWS)',
    category: 'devops',
    accent: '#FF9900',
    summary: 'Cloud platform for compute, storage, networking, and managed services at scale.',
    overview:
      'AWS provides a broad set of cloud services for building reliable, secure, and scalable systems. It’s a strong choice when you need production-ready infrastructure, global reach, and managed services that reduce operational load.',
    keyBenefits: ['Global scale', 'Managed services', 'Strong security primitives', 'Reliable infrastructure'],
    useCases: ['Web apps & APIs', 'Data platforms', 'High-availability systems', 'Enterprise infrastructure'],
    whyChoose: [
      'We design AWS architectures for reliability and cost efficiency.',
      'We implement secure IAM patterns and least-privilege access.',
      'We ship with observability, backups, and disaster recovery in mind.',
    ],
    related: ['amazon-ec2', 'amazon-rds', 'docker', 'ssl-tls'],
  },
  {
    slug: 'digitalocean',
    name: 'DigitalOcean',
    category: 'devops',
    accent: '#0080FF',
    summary: 'Developer-friendly cloud platform for simple, cost-effective deployments.',
    overview:
      'DigitalOcean is a pragmatic cloud platform that makes it easy to deploy apps quickly. It’s ideal for startups and teams that want simple infrastructure, predictable pricing, and a smooth developer experience.',
    keyBenefits: ['Simple deployments', 'Predictable pricing', 'Great DX', 'Fast setup'],
    useCases: ['MVP deployments', 'SMB infrastructure', 'Staging environments', 'Small-to-medium apps'],
    whyChoose: [
      'We keep infrastructure simple without sacrificing security.',
      'We automate deployments and backups for reliability.',
      'We scale resources as traffic grows.',
    ],
    related: ['docker', 'linux', 'ssl-tls', 'gcp'],
  },
  {
    slug: 'gcp',
    name: 'Google Cloud Platform (GCP)',
    category: 'devops',
    accent: '#4285F4',
    summary: 'Cloud platform with strong networking, data, and container capabilities.',
    overview:
      'GCP is a powerful cloud platform with strong networking and data services. It’s a great fit for teams building modern cloud-native systems and containerized workloads.',
    keyBenefits: ['Cloud-native strengths', 'Great networking', 'Strong data services', 'Containers-first tooling'],
    useCases: ['Cloud-native apps', 'Data platforms', 'Microservices', 'Global deployments'],
    whyChoose: [
      'We design secure, scalable GCP architectures.',
      'We implement CI/CD and observability best practices.',
      'We optimize performance and cost as systems evolve.',
    ],
    related: ['docker', 'linux', 'ssl-tls', 'aws'],
  },
  {
    slug: 'docker',
    name: 'Docker',
    category: 'devops',
    accent: '#2496ED',
    summary: 'Container platform for consistent builds and reliable deployments.',
    overview:
      'Docker standardizes how applications are packaged and shipped, making environments consistent from development to production. It’s foundational for modern CI/CD and scalable deployments.',
    keyBenefits: ['Consistent environments', 'Faster deployments', 'Portable builds', 'Great ecosystem'],
    useCases: ['CI/CD pipelines', 'Microservices', 'Local dev environments', 'Containerized deployments'],
    whyChoose: [
      'We build secure, minimal images for faster shipping.',
      'We standardize builds across services and teams.',
      'We integrate containers into reliable delivery pipelines.',
    ],
    related: ['linux', 'aws', 'gcp', 'ssl-tls'],
  },
  {
    slug: 'linux',
    name: 'Linux',
    category: 'devops',
    accent: '#111111',
    summary: 'The foundation OS for modern infrastructure and cloud workloads.',
    overview:
      'Linux powers the majority of cloud infrastructure. Understanding Linux fundamentals leads to more reliable deployments, better performance, and stronger operational practices.',
    keyBenefits: ['Stable foundation', 'Great performance', 'Strong tooling', 'Ubiquitous in cloud'],
    useCases: ['Servers', 'Containers', 'CI runners', 'Infrastructure automation'],
    whyChoose: [
      'We harden systems and lock down access properly.',
      'We tune performance for production workloads.',
      'We automate routine ops with reliable scripts and tools.',
    ],
    related: ['docker', 'ssl-tls', 'aws', 'gcp'],
  },
  {
    slug: 'ssl-tls',
    name: 'SSL/TLS',
    category: 'devops',
    accent: '#6B52A8',
    summary: 'Encryption protocols that secure traffic between clients and services.',
    overview:
      'SSL/TLS secures data in transit. Proper certificate management, secure ciphers, and strong defaults are essential for modern web and API security.',
    keyBenefits: ['Encrypted traffic', 'User trust', 'Compliance support', 'Security best practices'],
    useCases: ['Web apps', 'APIs', 'Service-to-service traffic', 'Edge security'],
    whyChoose: [
      'We automate certificate renewal and management.',
      'We enforce secure TLS configurations and headers.',
      'We reduce attack surface with modern crypto defaults.',
    ],
    related: ['aws', 'amazon-ec2', 'linux', 'docker'],
  },
  {
    slug: 'amazon-rds',
    name: 'Amazon RDS',
    category: 'devops',
    accent: '#527FFF',
    summary: 'Managed relational databases with backups, scaling, and high availability.',
    overview:
      'Amazon RDS is a managed database service that simplifies operations for relational databases. It’s ideal when you want reliability, backups, and scaling without running databases yourself.',
    keyBenefits: ['Managed backups', 'High availability', 'Scaling options', 'Operational simplicity'],
    useCases: ['Production databases', 'Multi-AZ systems', 'Read-heavy workloads', 'Secure data storage'],
    whyChoose: [
      'We set up backup, restore, and retention policies properly.',
      'We tune performance with indexes and sizing.',
      'We design for HA, security, and least-privilege access.',
    ],
    related: ['aws', 'amazon-ec2', 'ssl-tls', 'linux'],
  },
  {
    slug: 'amazon-ec2',
    name: 'Amazon EC2',
    category: 'devops',
    accent: '#FF9900',
    summary: 'Virtual compute instances for flexible workloads and custom infrastructure.',
    overview:
      'Amazon EC2 provides flexible compute capacity to run virtually any workload. It’s a core building block for systems that need custom environments or specific performance profiles.',
    keyBenefits: ['Flexible compute', 'Wide instance options', 'Mature ecosystem', 'Integrates with AWS services'],
    useCases: ['APIs', 'Workers & jobs', 'Legacy services', 'Custom infrastructure'],
    whyChoose: [
      'We right-size instances and implement autoscaling.',
      'We harden hosts and secure network boundaries.',
      'We automate provisioning with Infrastructure as Code.',
    ],
    related: ['aws', 'docker', 'linux', 'ssl-tls'],
  },
  {
    slug: 'amazon-ses',
    name: 'Amazon SES',
    category: 'devops',
    accent: '#FF9900',
    summary: 'Email sending service for reliable transactional and marketing communications.',
    overview:
      'Amazon SES is a scalable email service for transactional and bulk email. It’s a strong choice for product emails where deliverability and reliability matter.',
    keyBenefits: ['High deliverability', 'Scalable sending', 'Domain verification', 'Cost-effective'],
    useCases: ['Transactional email', 'Notifications', 'User onboarding', 'System alerts'],
    whyChoose: [
      'We set up DNS (SPF/DKIM/DMARC) correctly for deliverability.',
      'We implement templates and sending safeguards.',
      'We monitor bounces, complaints, and reputation.',
    ],
    related: ['aws', 'ssl-tls', 'amazon-ec2', 'linux'],
  },
  {
    slug: 'aws-amplify',
    name: 'AWS Amplify',
    category: 'devops',
    accent: '#FF9900',
    summary: 'Platform for building and deploying web apps with hosting, auth, and backend integrations.',
    overview:
      'AWS Amplify helps teams deploy and iterate on web apps quickly with hosting and backend integrations. It’s useful for fast delivery when paired with good architecture and CI/CD discipline.',
    keyBenefits: ['Fast deployments', 'Integrated hosting', 'Productivity boosts', 'AWS integrations'],
    useCases: ['Web app hosting', 'Rapid prototyping', 'Frontend deployments', 'Small teams shipping fast'],
    whyChoose: [
      'We wire CI/CD for predictable releases and rollbacks.',
      'We keep environments consistent across stages.',
      'We integrate auth and backend services securely.',
    ],
    related: ['aws', 'ssl-tls', 'docker', 'gcp'],
  },

  // E-commerce platforms
  {
    slug: 'shopify',
    name: 'Shopify',
    category: 'ecommerce',
    accent: '#95BF47',
    summary: 'E-commerce platform for fast launches with robust apps and themes.',
    overview:
      'Shopify is a leading e-commerce platform for building storefronts quickly with strong payments and ecosystem support. It’s ideal for brands that want fast iteration and reliable operations.',
    keyBenefits: ['Fast time-to-market', 'Strong ecosystem', 'Reliable checkout', 'Scales with growth'],
    useCases: ['DTC storefronts', 'Subscription commerce', 'Headless storefronts', 'International stores'],
    whyChoose: [
      'We build conversion-focused storefront experiences.',
      'We integrate payments, analytics, and fulfillment cleanly.',
      'We keep performance fast and UX consistent across devices.',
    ],
    related: ['woocommerce', 'bigcommerce', 'google-ads', 'seo'],
  },
  {
    slug: 'woocommerce',
    name: 'WooCommerce',
    category: 'ecommerce',
    accent: '#96588A',
    summary: 'WordPress commerce plugin for customizable stores and content-driven sales.',
    overview:
      'WooCommerce brings commerce to WordPress with flexibility and content-first workflows. It’s a strong fit for stores that need deep customization and strong editorial tooling.',
    keyBenefits: ['Highly customizable', 'WordPress ecosystem', 'Content + commerce', 'Ownership & control'],
    useCases: ['Content-first stores', 'SMB storefronts', 'Custom checkout flows', 'Integrated blogs & commerce'],
    whyChoose: [
      'We optimize themes and checkout for conversion.',
      'We harden security and keep updates maintainable.',
      'We tune performance for fast category and product pages.',
    ],
    related: ['wordpress', 'shopify', 'seo', 'mailchimp'],
  },
  {
    slug: 'magento',
    name: 'Magento',
    category: 'ecommerce',
    accent: '#F26322',
    summary: 'Enterprise commerce platform for complex catalogs and advanced workflows.',
    overview:
      'Magento is built for complex commerce: large catalogs, advanced pricing rules, and deep integrations. It’s a strong choice for enterprise commerce systems with specialized requirements.',
    keyBenefits: ['Enterprise capabilities', 'Complex catalogs', 'Custom workflows', 'Integration-ready'],
    useCases: ['Enterprise commerce', 'Multi-store setups', 'Complex pricing', 'ERP integrations'],
    whyChoose: [
      'We design scalable commerce architectures and integrations.',
      'We optimize performance for large catalogs.',
      'We maintain security and upgrade paths safely.',
    ],
    related: ['bigcommerce', 'shopify', 'docker', 'linux'],
  },
  {
    slug: 'bigcommerce',
    name: 'BigCommerce',
    category: 'ecommerce',
    accent: '#121118',
    summary: 'SaaS commerce platform built for performance and flexible integrations.',
    overview:
      'BigCommerce is a SaaS commerce platform that supports fast storefront builds and robust integrations. It’s a good fit for brands that want scalable commerce without heavy platform maintenance.',
    keyBenefits: ['SaaS simplicity', 'Good integrations', 'Scalable platform', 'Headless support'],
    useCases: ['Mid-market commerce', 'Headless storefronts', 'Multi-channel selling', 'B2B commerce'],
    whyChoose: [
      'We build fast storefronts with clean UX.',
      'We integrate catalog, payments, and analytics correctly.',
      'We keep tracking and attribution reliable.',
    ],
    related: ['shopify', 'magento', 'google-ads', 'seo'],
  },
  {
    slug: 'prestashop',
    name: 'PrestaShop',
    category: 'ecommerce',
    accent: '#DF0067',
    summary: 'Open-source e-commerce platform for customizable storefronts.',
    overview:
      'PrestaShop is an open-source commerce platform suited for customized storefronts and ownership-focused teams. It’s a practical option when you want control and flexibility.',
    keyBenefits: ['Open-source', 'Customizable', 'Ownership', 'Active ecosystem'],
    useCases: ['Custom storefronts', 'Regional commerce', 'Feature-rich stores', 'Self-hosted commerce'],
    whyChoose: [
      'We keep deployments secure and maintainable.',
      'We optimize performance and search behavior.',
      'We integrate payments and fulfillment reliably.',
    ],
    related: ['opencart', 'magento', 'docker', 'linux'],
  },
  {
    slug: 'opencart',
    name: 'OpenCart',
    category: 'ecommerce',
    accent: '#2AA3D9',
    summary: 'Lightweight open-source e-commerce platform for small-to-medium stores.',
    overview:
      'OpenCart is a lightweight commerce platform that can be extended through modules. It’s suited for smaller stores that need an owned solution without heavy complexity.',
    keyBenefits: ['Lightweight', 'Extendable', 'Self-hosted', 'Cost-effective'],
    useCases: ['SMB commerce', 'Regional stores', 'Simple catalogs', 'Custom modules'],
    whyChoose: [
      'We keep code clean to avoid module conflicts.',
      'We secure deployments and handle upgrades safely.',
      'We optimize for speed and conversion.',
    ],
    related: ['prestashop', 'woocommerce', 'linux', 'ssl-tls'],
  },
  {
    slug: 'nopcommerce',
    name: 'nopCommerce',
    category: 'ecommerce',
    accent: '#2E6E9E',
    summary: '.NET-based open-source e-commerce platform for extensible storefronts.',
    overview:
      'nopCommerce is an open-source e-commerce platform built on .NET. It’s a good choice for teams in the Microsoft ecosystem that need an extensible commerce base.',
    keyBenefits: ['.NET ecosystem', 'Extensible platform', 'Open-source', 'Enterprise-friendly'],
    useCases: ['B2B commerce', 'Microsoft-stack teams', 'Custom commerce workflows', 'Extensible storefronts'],
    whyChoose: [
      'We customize safely with upgrade paths in mind.',
      'We integrate with ERPs and payment gateways cleanly.',
      'We optimize performance for product discovery and checkout.',
    ],
    related: ['dotnet-core', 'magento', 'docker', 'linux'],
  },

  // CMS platforms / builders
  {
    slug: 'wordpress',
    name: 'WordPress',
    category: 'cms',
    accent: '#21759B',
    summary: 'CMS platform for publishing, marketing sites, and editorial workflows.',
    overview:
      'WordPress is a flexible CMS used for websites, landing pages, and content-heavy platforms. With good architecture and performance practices, it scales well and stays editor-friendly.',
    keyBenefits: ['Editor-friendly', 'Huge ecosystem', 'Flexible content', 'SEO capabilities'],
    useCases: ['Marketing sites', 'Blogs', 'Content platforms', 'Headless CMS setups'],
    whyChoose: [
      'We build clean, performant themes and blocks.',
      'We secure WordPress and manage updates responsibly.',
      'We model content to keep publishing fast and consistent.',
    ],
    related: ['woocommerce', 'elementor', 'seo', 'mailchimp'],
  },
  {
    slug: 'joomla',
    name: 'Joomla',
    category: 'cms',
    accent: '#5091CD',
    summary: 'Flexible CMS for structured content and extensible site builds.',
    overview:
      'Joomla is a capable CMS with extensibility and structured content features. It’s often used when teams need flexible templates and content management beyond basic pages.',
    keyBenefits: ['Flexible templates', 'Extensible', 'Structured content', 'Role-based access'],
    useCases: ['Company sites', 'Portals', 'Content platforms', 'Multi-user publishing'],
    whyChoose: [
      'We structure templates and modules cleanly.',
      'We harden deployments and keep updates safe.',
      'We optimize performance and caching behavior.',
    ],
    related: ['wordpress', 'webflow', 'ssl-tls', 'linux'],
  },
  {
    slug: 'wix',
    name: 'Wix',
    category: 'cms',
    accent: '#111111',
    summary: 'Website builder for fast launches with templates and hosted management.',
    overview:
      'Wix is a hosted website builder for fast launches. It’s useful when teams want quick publishing and simple site management without managing infrastructure.',
    keyBenefits: ['Fast setup', 'Hosted management', 'Template-driven', 'Simple editing'],
    useCases: ['Small business sites', 'Landing pages', 'Portfolios', 'Fast MVP sites'],
    whyChoose: [
      'We design layouts that stay clean and on-brand.',
      'We optimize content structure for SEO basics.',
      'We keep interactions and copy conversion-focused.',
    ],
    related: ['squarespace', 'webflow', 'seo', 'canva'],
  },
  {
    slug: 'webflow',
    name: 'Webflow',
    category: 'cms',
    accent: '#146EF5',
    summary: 'Visual web design + CMS for high-quality marketing sites and content.',
    overview:
      'Webflow combines visual design control with CMS capabilities. It’s a strong choice for premium marketing sites with responsive design and fast publishing workflows.',
    keyBenefits: ['Design control', 'Responsive by default', 'CMS + hosting', 'Fast publishing'],
    useCases: ['Marketing sites', 'Landing pages', 'Content sections', 'Brand sites'],
    whyChoose: [
      'We build scalable component-like systems in Webflow.',
      'We keep performance and responsiveness tight.',
      'We structure CMS collections for easy publishing.',
    ],
    related: ['figma', 'seo', 'google-ads', 'mailchimp'],
  },
  {
    slug: 'squarespace',
    name: 'Squarespace',
    category: 'cms',
    accent: '#111111',
    summary: 'Website builder for beautiful templates and simple site management.',
    overview:
      'Squarespace offers polished templates and easy editing. It’s suitable for teams that want simple site management and a clean look with minimal setup.',
    keyBenefits: ['Beautiful templates', 'Easy editing', 'Hosted management', 'Fast launch'],
    useCases: ['Portfolios', 'Small business sites', 'Landing pages', 'Content sites'],
    whyChoose: [
      'We customize design within template constraints thoughtfully.',
      'We keep content structure clean and conversion-focused.',
      'We ensure the site remains consistent across devices.',
    ],
    related: ['wix', 'webflow', 'seo', 'canva'],
  },
  {
    slug: 'elementor',
    name: 'Elementor',
    category: 'cms',
    accent: '#92003B',
    summary: 'WordPress visual builder for rapid page creation and reusable blocks.',
    overview:
      'Elementor is a popular WordPress page builder that enables fast page creation. It’s effective when teams need quick iteration with reusable blocks and templates.',
    keyBenefits: ['Rapid layout building', 'Reusable templates', 'Editor-friendly', 'WordPress ecosystem'],
    useCases: ['Landing pages', 'Marketing pages', 'Campaign pages', 'Rapid iterations'],
    whyChoose: [
      'We keep templates reusable and consistent.',
      'We optimize assets to keep pages fast.',
      'We maintain clean structure for future changes.',
    ],
    related: ['wordpress', 'wpbakery', 'brizy', 'seo'],
  },
  {
    slug: 'wpbakery',
    name: 'WPBakery',
    category: 'cms',
    accent: '#00A0D2',
    summary: 'WordPress page builder for structured layouts and visual editing workflows.',
    overview:
      'WPBakery is a widely used WordPress builder for structured layouts. It’s helpful for maintaining existing sites and building consistent page patterns quickly.',
    keyBenefits: ['Visual editing', 'Reusable patterns', 'Wide adoption', 'Works with many themes'],
    useCases: ['Existing WordPress sites', 'Marketing pages', 'Reusable landing layouts', 'Content blocks'],
    whyChoose: [
      'We keep page structures consistent and maintainable.',
      'We reduce bloat by optimizing assets.',
      'We ensure responsive behavior and accessibility basics.',
    ],
    related: ['wordpress', 'elementor', 'brizy', 'seo'],
  },
  {
    slug: 'brizy',
    name: 'Brizy',
    category: 'cms',
    accent: '#FF5B3D',
    summary: 'WordPress builder focused on simple, fast visual editing and templates.',
    overview:
      'Brizy is a builder that emphasizes simplicity and speed. It’s useful for teams that want quick page creation with a straightforward editing experience.',
    keyBenefits: ['Simple UI', 'Fast editing', 'Templates', 'WordPress integration'],
    useCases: ['Landing pages', 'Small sites', 'Campaign pages', 'Rapid updates'],
    whyChoose: [
      'We create reusable templates to keep brand consistency.',
      'We keep pages light and performance-friendly.',
      'We ensure mobile responsiveness stays clean.',
    ],
    related: ['wordpress', 'elementor', 'seo', 'canva'],
  },

  // Digital marketing
  {
    slug: 'google-ads',
    name: 'Google Ads',
    category: 'marketing',
    accent: '#4285F4',
    summary: 'Paid search and display campaigns for demand capture and acquisition.',
    overview:
      'Google Ads enables high-intent acquisition via search and scalable reach via display. It’s ideal when teams want measurable, performance-driven growth.',
    keyBenefits: ['High-intent targeting', 'Measurable ROI', 'Scalable reach', 'Strong analytics'],
    useCases: ['Lead gen', 'E-commerce acquisition', 'Brand campaigns', 'Retargeting'],
    whyChoose: [
      'We build tracking that matches attribution reality.',
      'We craft landing pages for conversion and speed.',
      'We optimize campaigns with clean reporting loops.',
    ],
    related: ['seo', 'youtube-ads', 'mailchimp', 'x'],
  },
  {
    slug: 'seo',
    name: 'SEO',
    category: 'marketing',
    accent: '#1E8A6E',
    summary: 'Search engine optimization for sustainable organic growth.',
    overview:
      'SEO builds long-term demand by improving discoverability, content quality, and technical performance. It’s foundational for sustainable marketing growth.',
    keyBenefits: ['Sustainable traffic', 'Compounding results', 'Better site quality', 'Strong intent capture'],
    useCases: ['Content strategy', 'Technical SEO', 'On-page optimization', 'Performance improvements'],
    whyChoose: [
      'We align technical + content work for measurable outcomes.',
      'We fix performance and indexing blockers.',
      'We track progress with clean, understandable metrics.',
    ],
    related: ['google-ads', 'webflow', 'wordpress', 'mailchimp'],
  },
  {
    slug: 'facebook-ads',
    name: 'Facebook Ads',
    category: 'marketing',
    accent: '#1877F2',
    summary: 'Paid social campaigns for targeting, acquisition, and retargeting.',
    overview:
      'Facebook Ads provide powerful audience targeting and retargeting for performance campaigns. It’s useful for both acquisition and brand awareness when paired with strong creative.',
    keyBenefits: ['Audience targeting', 'Retargeting', 'Creative testing', 'Scalable acquisition'],
    useCases: ['E-commerce', 'Lead gen', 'Retargeting', 'Brand campaigns'],
    whyChoose: [
      'We set up tracking and events correctly.',
      'We build creative and landing pages that convert.',
      'We optimize with disciplined experimentation.',
    ],
    related: ['instagram-ads', 'pinterest-ads', 'snapchat-ads', 'mailchimp'],
  },
  {
    slug: 'linkedin-ads',
    name: 'LinkedIn Ads',
    category: 'marketing',
    accent: '#0A66C2',
    summary: 'B2B targeting for lead generation and account-based marketing.',
    overview:
      'LinkedIn Ads are ideal for B2B acquisition and account-based marketing. They’re effective when targeting job titles, industries, and company segments.',
    keyBenefits: ['B2B targeting', 'ABM-friendly', 'Lead gen forms', 'Professional context'],
    useCases: ['B2B lead gen', 'ABM campaigns', 'Webinars', 'Enterprise acquisition'],
    whyChoose: [
      'We match messaging to audience intent.',
      'We build landing flows for lead capture.',
      'We optimize for quality leads, not vanity metrics.',
    ],
    related: ['google-ads', 'mailchimp', 'seo', 'x'],
  },
  {
    slug: 'youtube-ads',
    name: 'YouTube Ads',
    category: 'marketing',
    accent: '#FF0000',
    summary: 'Video campaigns for awareness, consideration, and retargeting.',
    overview:
      'YouTube Ads enable video-based reach at scale, paired with targeting and retargeting. Great for storytelling and top-of-funnel demand generation.',
    keyBenefits: ['Video reach', 'Brand lift', 'Retargeting', 'Scalable awareness'],
    useCases: ['Awareness campaigns', 'Product explainers', 'Retargeting', 'Launches'],
    whyChoose: [
      'We align creative to funnel stage.',
      'We optimize targeting and frequency.',
      'We track outcomes with clean reporting.',
    ],
    related: ['google-ads', 'instagram-ads', 'x', 'seo'],
  },
  {
    slug: 'pinterest-ads',
    name: 'Pinterest Ads',
    category: 'marketing',
    accent: '#E60023',
    summary: 'Discovery-based ads for inspiration-driven audiences and purchases.',
    overview:
      'Pinterest Ads target users in discovery mode. It’s effective for brands with strong visuals and products that benefit from inspiration-led browsing.',
    keyBenefits: ['Discovery intent', 'Visual-first', 'Evergreen content', 'Great for certain niches'],
    useCases: ['E-commerce', 'Lifestyle brands', 'Content discovery', 'Seasonal campaigns'],
    whyChoose: [
      'We design creative that matches platform behavior.',
      'We optimize campaigns around catalog and product signals.',
      'We measure conversions with clean attribution.',
    ],
    related: ['facebook-ads', 'instagram-ads', 'google-ads', 'seo'],
  },
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    category: 'marketing',
    accent: '#FFE01B',
    summary: 'Email marketing platform for campaigns, automation, and audience management.',
    overview:
      'Mailchimp supports email campaigns and automations for nurturing and retention. It’s a strong fit for teams that want a reliable email workflow with good templates and segmentation.',
    keyBenefits: ['Automations', 'Segmentation', 'Templates', 'Analytics'],
    useCases: ['Newsletter', 'Onboarding sequences', 'Retention campaigns', 'Promotions'],
    whyChoose: [
      'We build email systems that match lifecycle stages.',
      'We improve deliverability with best-practice setup.',
      'We connect tracking and lists cleanly.',
    ],
    related: ['amazon-ses', 'seo', 'google-ads', 'facebook-ads'],
  },
  {
    slug: 'snapchat-ads',
    name: 'Snapchat Ads',
    category: 'marketing',
    accent: '#FFFC00',
    summary: 'Paid social for short-form creative, acquisition, and retargeting.',
    overview:
      'Snapchat Ads are effective for younger demographics and short-form creative testing. It’s useful for direct-response campaigns with fast iteration.',
    keyBenefits: ['Short-form creative', 'Fast testing', 'Audience reach', 'Retargeting'],
    useCases: ['App installs', 'E-commerce', 'Brand awareness', 'Creative experiments'],
    whyChoose: [
      'We iterate creative quickly and measure outcomes.',
      'We tune audiences and conversions events.',
      'We keep reporting clear and actionable.',
    ],
    related: ['instagram-ads', 'facebook-ads', 'google-ads', 'x'],
  },
  {
    slug: 'instagram-ads',
    name: 'Instagram Ads',
    category: 'marketing',
    accent: '#C13584',
    summary: 'Visual-first paid social for acquisition, engagement, and retargeting.',
    overview:
      'Instagram Ads are great for visual storytelling and performance campaigns. It’s effective when paired with strong creative and fast landing experiences.',
    keyBenefits: ['Visual storytelling', 'Creative formats', 'Retargeting', 'Scalable acquisition'],
    useCases: ['E-commerce', 'Brand campaigns', 'Product launches', 'Retargeting'],
    whyChoose: [
      'We design creatives that match the platform and audience.',
      'We optimize landing flows for mobile conversion.',
      'We measure performance with clean tracking setups.',
    ],
    related: ['facebook-ads', 'pinterest-ads', 'youtube-ads', 'mailchimp'],
  },
  {
    slug: 'x',
    name: 'X',
    category: 'marketing',
    accent: '#111111',
    summary: 'Campaigns for awareness, conversation, and audience-driven distribution.',
    overview:
      'X is useful for real-time distribution, community engagement, and targeted campaigns. When paired with good creative and clear messaging, it can amplify launches and content quickly.',
    keyBenefits: ['Real-time distribution', 'Conversation-driven reach', 'Targeting options', 'Fast feedback loops'],
    useCases: ['Product launches', 'Brand awareness', 'Event promotion', 'Content amplification'],
    whyChoose: [
      'We craft messaging that matches the platform’s rhythm.',
      'We optimize creative and targeting for clarity.',
      'We measure impact with practical KPIs.',
    ],
    related: ['google-ads', 'linkedin-ads', 'youtube-ads', 'seo'],
  },

  // AI & Machine Learning
  {
    slug: 'openai',
    name: 'OpenAI (GPT)',
    category: 'ai-machine-learning',
    accent: '#10A37F',
    summary: 'Industry-leading LLMs for text generation, reasoning, and intelligent product features.',
    overview: 'OpenAI GPT models power a wide range of AI-driven features from conversational interfaces and content generation to code assistance and complex reasoning. We integrate OpenAI APIs into products that need reliable, high-quality language intelligence.',
    keyBenefits: ['State-of-the-art language models', 'Flexible API integration', 'Function calling & structured output', 'Vision and multimodal support'],
    useCases: ['AI chatbots & assistants', 'Content generation pipelines', 'Code review automation', 'Document analysis'],
    whyChoose: [
      'We design prompts and system instructions that produce consistent, reliable outputs.',
      'We implement cost controls, caching, and fallback strategies for production use.',
      'We build safe, observable AI features with logging and evaluation loops.',
    ],
    related: ['vibe-coding', 'google-gemini', 'generative-ai', 'n8n', 'make'],
  },
  {
    slug: 'vibe-coding',
    name: 'Vibe Coding',
    category: 'ai-machine-learning',
    accent: '#6366F1',
    summary:
      'Next-Gen AI-Powered Development Experience — AI-assisted engineering that blends intelligent suggestions, automation, and workflow optimisation so teams ship faster without losing craft.',
    overview:
      'Vibe Coding is an AI-assisted development approach where intelligent tooling, automation, and contextual suggestions amplify how teams design, build, and ship software. It prioritises developer experience, iteration speed, and creative flow — pairing human judgment with models, agents, and workflow automation so engineers spend less time on boilerplate and more time on product decisions.\n\nWe help teams adopt Vibe Coding patterns responsibly: clear review gates, measurable quality checks, and architectures that stay maintainable as AI capabilities evolve.',
    keyBenefits: [
      'Intelligent code suggestions',
      'Real-time automation',
      'Context-aware development',
      'Faster debugging & optimisation',
      'Seamless developer workflow',
    ],
    useCases: [
      'Rapid product development',
      'AI-powered SaaS platforms',
      'Automation-heavy applications',
      'Startup MVP development',
      'Enterprise workflow automation',
    ],
    whyChoose: [
      'Faster development cycles without sacrificing review discipline, with less manual effort on repetitive implementation tasks.',
      'High scalability patterns that grow from prototype to production while staying observable in production.',
      'Future-ready approach as models, IDEs, and agents improve — with architectures we can evolve safely.',
    ],
    related: ['openai', 'generative-ai', 'google-gemini', 'claude'],
  },
  {
    slug: 'google-gemini',
    name: 'Google Gemini',
    category: 'ai-machine-learning',
    accent: '#4285F4',
    summary: 'Google multimodal AI model for text, image, audio, and code understanding.',
    overview: 'Google Gemini is a multimodal foundation model that handles text, images, audio, and code in a unified architecture. It integrates naturally with Google Cloud and is a strong choice for teams already in the GCP ecosystem.',
    keyBenefits: ['Multimodal understanding', 'Google Cloud integration', 'Long context window', 'Strong reasoning capabilities'],
    useCases: ['Document and image analysis', 'Multimodal search', 'Code generation', 'Enterprise AI on GCP'],
    whyChoose: [
      'We leverage Gemini multimodal strengths for richer product experiences.',
      'We integrate with Vertex AI for scalable, managed model serving.',
      'We evaluate model outputs systematically before shipping to production.',
    ],
    related: ['openai', 'generative-ai', 'n8n', 'make'],
  },
  {
    slug: 'generative-ai',
    name: 'Generative AI',
    category: 'ai-machine-learning',
    accent: '#7C3AED',
    summary: 'AI systems that generate text, images, code, and media from learned patterns.',
    overview: 'Generative AI encompasses the models and techniques behind content creation, from LLMs and diffusion models to multimodal systems. We help teams identify where generative AI creates real product value and build it responsibly.',
    keyBenefits: ['Content generation at scale', 'Multimodal capabilities', 'Personalization', 'Automation of creative tasks'],
    useCases: ['AI content pipelines', 'Image and media generation', 'Personalized experiences', 'Automated reporting'],
    whyChoose: [
      'We evaluate generative AI use cases for real ROI before committing to build.',
      'We implement guardrails, content filtering, and human review where needed.',
      'We design systems that stay reliable as underlying models evolve.',
    ],
    related: ['openai', 'google-gemini', 'ai-bot', 'n8n'],
  },
  {
    slug: 'n8n',
    name: 'n8n',
    category: 'ai-machine-learning',
    accent: '#EA4B71',
    summary: 'Open-source workflow automation tool for connecting AI and business processes.',
    overview: 'n8n is a powerful open-source automation platform that lets teams build complex workflows connecting AI models, APIs, and business tools. It is ideal for automating repetitive tasks and building AI-powered pipelines without heavy engineering overhead.',
    keyBenefits: ['Visual workflow builder', 'Self-hostable & open-source', '400+ integrations', 'AI-native nodes'],
    useCases: ['AI workflow automation', 'Data pipeline orchestration', 'CRM & marketing automation', 'AI agent workflows'],
    whyChoose: [
      'We design reliable, maintainable automation workflows that scale with your business.',
      'We integrate n8n with OpenAI, databases, and third-party APIs cleanly.',
      'We self-host and secure n8n deployments for data-sensitive environments.',
    ],
    related: ['make', 'openai', 'google-gemini', 'ai-bot'],
  },
  {
    slug: 'make',
    name: 'Make.com',
    category: 'ai-machine-learning',
    accent: '#6D00CC',
    summary: 'Visual automation platform for building powerful no-code AI and business workflows.',
    overview: 'Make.com (formerly Integromat) is a visual automation platform that enables teams to connect apps and automate workflows without writing code. It is a strong choice for rapid automation of AI-powered processes and business integrations.',
    keyBenefits: ['Visual drag-and-drop builder', '1000+ app integrations', 'AI & LLM modules', 'Real-time execution'],
    useCases: ['AI-powered automations', 'Lead & CRM workflows', 'Content generation pipelines', 'Multi-app integrations'],
    whyChoose: [
      'We build robust Make scenarios that handle errors and edge cases gracefully.',
      'We connect AI models to your existing tools for seamless automation.',
      'We design workflows that are easy for your team to maintain and extend.',
    ],
    related: ['n8n', 'openai', 'google-gemini', 'ai-bot'],
  },
  {
    slug: 'claude',
    name: 'Claude',
    category: 'ai-machine-learning',
    accent: '#D97757',
    summary: 'Anthropic\'s safety-focused LLM for reliable, nuanced AI conversations and tasks.',
    overview: 'Claude is Anthropic\'s AI assistant built with a focus on safety, honesty, and helpfulness. It excels at long-context reasoning, document analysis, and nuanced conversations — making it a strong choice for enterprise AI features that require trustworthy outputs.',
    keyBenefits: ['Long context window', 'Safety-first design', 'Strong reasoning & analysis', 'Reliable instruction following'],
    useCases: ['Document summarization', 'Customer support automation', 'Code review & generation', 'Research & analysis tools'],
    whyChoose: [
      'We integrate Claude where output reliability and safety are non-negotiable.',
      'We leverage its long context for document-heavy workflows.',
      'We evaluate Claude alongside other LLMs to pick the right model for your task.',
    ],
    related: ['openai', 'google-gemini', 'generative-ai', 'ai-bot'],
  },
  {
    slug: 'ai-bot',
    name: 'AI Bot',
    category: 'ai-machine-learning',
    accent: '#0EA5E9',
    summary: 'Custom AI-powered chatbots and assistants for business automation and customer engagement.',
    overview: 'AI Bots are intelligent conversational agents built on top of LLMs like GPT and Gemini. We design and develop custom AI bots for customer support, lead generation, internal tools, and workflow automation — tailored to your business needs.',
    keyBenefits: ['24/7 automated responses', 'Custom knowledge base', 'Multi-channel deployment', 'Human handoff support'],
    useCases: ['Customer support bots', 'Lead qualification', 'Internal HR & IT assistants', 'E-commerce product advisors'],
    whyChoose: [
      'We design bot conversation flows that feel natural and on-brand.',
      'We integrate custom knowledge bases for accurate, context-aware responses.',
      'We build with fallback and escalation paths so users always get help.',
    ],
    related: ['openai', 'google-gemini', 'n8n', 'make'],
  },

  // Database
  {
    slug: 'mongodb',
    name: 'MongoDB',
    category: 'database',
    accent: '#47A248',
    summary: 'Document database for flexible schemas and fast iteration at scale.',
    overview:
      'MongoDB is a popular document database for applications that evolve quickly. It fits product teams that need flexible schemas, horizontal scaling patterns, and developer-friendly query models.',
    keyBenefits: ['Flexible documents', 'Horizontal scaling patterns', 'Rich query API', 'Strong ecosystem'],
    useCases: ['Product catalogs', 'Content platforms', 'Real-time apps', 'Analytics pipelines'],
    whyChoose: [
      'We model data for performance and maintainability.',
      'We design indexes and access patterns intentionally.',
      'We pair MongoDB with solid backup and observability practices.',
    ],
    related: ['redis', 'postgresql', 'nodejs', 'graphql'],
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    category: 'database',
    accent: '#3ECF8E',
    summary: 'Open-source Firebase alternative with Postgres, auth, and realtime APIs.',
    overview:
      'Supabase combines PostgreSQL with auth, storage, and generated APIs. It accelerates delivery when you want a managed backend without sacrificing SQL fundamentals.',
    keyBenefits: ['Postgres-first', 'Auth & storage', 'Realtime channels', 'Fast prototyping'],
    useCases: ['MVPs', 'Internal tools', 'Consumer apps', 'Realtime dashboards'],
    whyChoose: [
      'We keep schemas clean and migrations disciplined.',
      'We secure Row Level Security policies and keys properly.',
      'We integrate Supabase with modern front-end frameworks smoothly.',
    ],
    related: ['postgresql', 'firebase', 'prisma', 'nextjs'],
  },
  {
    slug: 'mysql',
    name: 'MySQL',
    category: 'database',
    accent: '#4479A1',
    summary: 'Widely adopted relational database for web applications and transactional workloads.',
    overview:
      'MySQL remains a dependable choice for transactional workloads, CMS data, and classic LAMP-style stacks. With good schema design and indexing, it stays fast at scale.',
    keyBenefits: ['Mature ecosystem', 'Replication topologies', 'Broad hosting support', 'SQL familiarity'],
    useCases: ['E-commerce', 'CMS-backed sites', 'SaaS data stores', 'Reporting'],
    whyChoose: [
      'We optimize queries, indexes, and connection usage.',
      'We plan backups and recovery with clear RPO/RTO.',
      'We align schema design with application access patterns.',
    ],
    related: ['postgresql', 'redis', 'php', 'wordpress'],
  },
  {
    slug: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    accent: '#4169E1',
    summary: 'Advanced open-source relational database with strong SQL and extension ecosystem.',
    overview:
      'PostgreSQL is a powerhouse for complex queries, constraints, and extension-driven features. It is a strong default for SaaS backends that need correctness and flexibility.',
    keyBenefits: ['Rich SQL', 'JSON support', 'Extensions', 'Strong consistency'],
    useCases: ['SaaS platforms', 'Financial workflows', 'Geospatial', 'Analytics'],
    whyChoose: [
      'We design schemas and migrations with long-term maintainability.',
      'We tune indexes and planner behavior for real workloads.',
      'We use Postgres features when they reduce complexity elsewhere.',
    ],
    related: ['mysql', 'prisma', 'redis', 'supabase'],
  },
  {
    slug: 'firebase',
    name: 'Firebase',
    category: 'database',
    accent: '#FFCA28',
    summary: 'Google-backed platform for auth, realtime data, hosting, and mobile backends.',
    overview:
      'Firebase helps teams ship quickly with hosted auth, Firestore/Realtime Database, and cloud functions. It shines for mobile-first products and rapid iteration.',
    keyBenefits: ['Fast setup', 'Realtime sync', 'Mobile SDKs', 'Integrated auth'],
    useCases: ['Mobile apps', 'Prototypes', 'Live dashboards', 'Chat features'],
    whyChoose: [
      'We structure security rules carefully from day one.',
      'We plan for cost and read/write patterns as you scale.',
      'We integrate Firebase with clean client architectures.',
    ],
    related: ['supabase', 'mongodb', 'react-native', 'flutter'],
  },
  {
    slug: 'prisma',
    name: 'Prisma',
    category: 'database',
    accent: '#2D3748',
    summary: 'Type-safe ORM and migrations for Node.js and modern TypeScript services.',
    overview:
      'Prisma improves developer experience with schema-first modeling, migrations, and type-safe queries. It pairs naturally with Node/TypeScript backends.',
    keyBenefits: ['Type-safe queries', 'Migrations', 'Great DX', 'Multi-database support'],
    useCases: ['Node APIs', 'Next.js backends', 'Microservices', 'Internal tools'],
    whyChoose: [
      'We keep Prisma schemas aligned with product boundaries.',
      'We optimize N+1 patterns and connection pooling.',
      'We integrate migrations into CI/CD safely.',
    ],
    related: ['postgresql', 'mysql', 'nodejs', 'nextjs'],
  },
  {
    slug: 'redis',
    name: 'Redis',
    category: 'database',
    accent: '#DC382D',
    summary: 'In-memory data store for cache, queues, sessions, and realtime features.',
    overview:
      'Redis is the go-to for caching, rate limiting, pub/sub, and fast ephemeral state. Used well, it dramatically improves latency and protects primary databases.',
    keyBenefits: ['Ultra-low latency', 'Versatile data structures', 'Pub/sub', 'Battle-tested'],
    useCases: ['Caching', 'Sessions', 'Queues', 'Leaderboards'],
    whyChoose: [
      'We define TTLs and eviction policies deliberately.',
      'We avoid cache stampedes and hot-key issues.',
      'We monitor memory usage and failover behavior.',
    ],
    related: ['mongodb', 'postgresql', 'nodejs', 'aws'],
  },
];

