export const SERVICES_DATA = [
  {
    id: 1,
    slug: 'ai-automation',
    title: 'AI & Automation',
    tag: 'Intelligence',
    shortDescription: 'LLMs, ML pipelines, and intelligent automation that turn data into product experiences.',
    navDescription: 'LLMs, ML pipelines & gen AI.',
    fullDescription:
      'We integrate and build with the leading AI and ML technologies — from OpenAI and Gemini to automation platforms like n8n and Make — so your product can leverage intelligent features that are reliable, observable, and built to evolve.',
    icon: 'Brain',
    accent: '#4A6FA5',
    bg: '#D8E4F5',
    illustration: 'web',
    process: [
      { step: '01', title: 'Evaluate', desc: 'Use case validation, model selection, and feasibility.' },
      { step: '02', title: 'Prototype', desc: 'Rapid iteration on prompts, pipelines, and retrieval.' },
      { step: '03', title: 'Harden', desc: 'Evaluation datasets, guardrails, and cost optimization.' },
      { step: '04', title: 'Ship', desc: 'Deploy, monitor, and iterate on AI behavior in production.' },
    ],
    technologies: ['Vibe Coding', 'OpenAI', 'Google Gemini', 'n8n', 'Make', 'Claude'],
    features: ['LLM integration & prompt engineering', 'RAG pipelines with vector search', 'AI agent architectures', 'Workflow automation', 'Embedding & semantic search', 'Responsible AI & output guardrails'],
    benefits: [
      { title: 'Production-ready AI', desc: 'AI features with observability, fallbacks, and cost controls from day one.', icon: '🤖' },
      { title: 'Right model, right task', desc: 'We match the model to the problem — not the hype cycle.', icon: '🎯' },
      { title: 'Evolves with the field', desc: 'Architectures designed to swap models as better ones emerge.', icon: '🔄' },
    ],
    techSubtitle: 'AI platforms and automation tools we use to build intelligent product experiences.',
    techPanels: [
      { title: 'AI & Automation Stack', slugs: ['vibe-coding', 'openai', 'google-gemini', 'generative-ai', 'n8n', 'make', 'ai-bot', 'claude'] },
    ],
  },
  {
    id: 2,
    slug: 'web-application-development',
    title: 'Web Application Development',
    tag: 'Engineering',
    shortDescription: 'Custom web apps built with modern frameworks — fast, accessible, and scalable.',
    navDescription: 'Dashboards, SaaS platforms & scalable web apps.',
    fullDescription:
      'We build high-quality web applications that feel premium: fast to load, delightful to use, and engineered to scale. From dashboards to SaaS platforms, every build is designed for reliability and long-term maintainability.',
    icon: 'Code2',
    accent: '#A07830',
    bg: '#FDF8F0',
    illustration: 'web',
    process: [
      { step: '01', title: 'Discovery', desc: 'Clarify goals, users, and success metrics.' },
      { step: '02', title: 'System Design', desc: 'Architecture, data model, and UX flow planning.' },
      { step: '03', title: 'Build', desc: 'Iterative sprints with demos and continuous integration.' },
      { step: '04', title: 'Launch', desc: 'Deployment, monitoring, and post-launch iteration.' },
    ],
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'GraphQL', 'Docker', 'AWS', 'TYPO3'],
    features: ['SaaS platforms', 'Dashboards & analytics', 'API development', 'Auth & roles', 'Performance optimization', 'Maintenance & upgrades'],
    benefits: [
      { title: 'Fast & Accessible', desc: 'Performance and UX that keep users engaged.', icon: '⚡' },
      { title: 'Scales with you', desc: 'Architecture that grows without rewrites.', icon: '📈' },
      { title: 'Maintainable', desc: 'Clean, tested code and documented systems.', icon: '🧩' },
    ],
    techSubtitle: 'Categorized by where they shine — click a logo to explore details.',
    techPanels: [
      { title: 'Frontend Technologies', slugs: ['reactjs', 'vuejs', 'nextjs', 'nuxtjs', 'vite', 'angular', 'html-bootstrap'] },
      { title: 'Backend Technologies', slugs: ['typo3', 'nodejs', 'nestjs', 'php', 'dotnet-core', 'python-django', 'graphql'] },
    ],
  },
  {
    id: 2,
    slug: 'mobile-app-development',
    title: 'Mobile App Development',
    tag: 'Engineering',
    shortDescription: 'Native & cross-platform mobile experiences that ship with polish and performance.',
    navDescription: 'iOS & Android apps built for retention.',
    fullDescription:
      'We deliver iOS and Android apps built for retention: smooth interactions, thoughtful UX, and production-grade engineering. From MVP to App Store, we ship mobile products that users love.',
    icon: 'Smartphone',
    accent: '#2E6E9E',
    bg: '#F0F5FA',
    illustration: 'mobile',
    process: [
      { step: '01', title: 'UX Strategy', desc: 'User journeys, flows, and prototypes.' },
      { step: '02', title: 'Design', desc: 'Pixel-perfect UI with a reusable component system.' },
      { step: '03', title: 'Development', desc: 'Native or cross-platform build with performance focus.' },
      { step: '04', title: 'Launch & Iterate', desc: 'Store release, analytics, and continuous improvements.' },
    ],
    technologies: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase', 'Expo'],
    features: ['iOS & Android', 'Cross-platform builds', 'Offline-first', 'Push notifications', 'Payments & subscriptions', 'Performance profiling'],
    benefits: [
      { title: 'High performance', desc: 'Apps that feel fast and fluid.', icon: '🏎️' },
      { title: 'Premium polish', desc: 'UI details that make brands feel trusted.', icon: '✨' },
      { title: 'Faster delivery', desc: 'Agile sprints with transparent progress.', icon: '🚀' },
    ],
    techSubtitle: 'Native and cross-platform stacks — click a logo to explore details.',
    techPanels: [
      { title: 'Native Development', slugs: ['android', 'ios', 'swift', 'kotlin', 'java', 'objective-c'] },
      { title: 'Cross-Platform Development', slugs: ['react-native', 'flutter', 'ionic'] },
    ],
  },
  {
    id: 3,
    slug: 'devops',
    title: 'DevOps',
    tag: 'Infrastructure',
    shortDescription: 'CI/CD, containers, and cloud infrastructure that keeps releases safe and fast.',
    navDescription: 'Pipelines, containers & cloud infra.',
    fullDescription:
      'We build modern delivery pipelines and cloud infrastructure so teams ship confidently. From CI/CD to monitoring and incident readiness, we make reliability a default — not a hope.',
    icon: 'GitBranch',
    accent: '#1E8A6E',
    bg: '#F0FAF6',
    illustration: 'devops',
    process: [
      { step: '01', title: 'Audit', desc: 'Review current infra, delivery, and bottlenecks.' },
      { step: '02', title: 'Pipeline', desc: 'Automated CI/CD with quality gates.' },
      { step: '03', title: 'Infra', desc: 'Containers, IaC, and secure deployment patterns.' },
      { step: '04', title: 'Observe', desc: 'Monitoring, alerting, and runbooks.' },
    ],
    technologies: ['Docker', 'AWS', 'Linux', 'GCP', 'DigitalOcean'],
    features: ['CI/CD pipelines', 'Infrastructure as Code', 'Containers & orchestration', 'Monitoring & alerts', 'Security hardening', 'Cost optimization'],
    benefits: [
      { title: 'Safer releases', desc: 'Automated checks and rollbacks.', icon: '🛡️' },
      { title: 'Faster shipping', desc: 'Shorter lead time from commit to prod.', icon: '⚙️' },
      { title: 'Always-on', desc: 'Observability that catches issues early.', icon: '🌐' },
    ],
    techSubtitle: 'Infrastructure, cloud, and delivery tooling we use to ship reliably.',
    techPanels: [
      { title: 'DevOps Stack', slugs: ['aws', 'digitalocean', 'gcp', 'docker', 'linux', 'ssl-tls', 'amazon-rds', 'amazon-ec2', 'amazon-ses', 'aws-amplify'] },
    ],
  },
  {
    id: 4,
    slug: 'ui-ux-design-and-development',
    title: 'UI/UX Design & Development',
    tag: 'Design',
    shortDescription: 'Design + implementation that feels cohesive — usable, accessible, and conversion-minded.',
    navDescription: 'Research-led UX with pixel-perfect UI.',
    fullDescription:
      'We blend research-led UX with high-fidelity UI and front-end implementation. The result is a consistent, scalable product experience that looks modern and performs beautifully.',
    icon: 'Palette',
    accent: '#6B52A8',
    bg: '#F4F1FA',
    illustration: 'design',
    process: [
      { step: '01', title: 'Research', desc: 'User needs, competitors, and usability insights.' },
      { step: '02', title: 'Design system', desc: 'Components, typography, and interaction rules.' },
      { step: '03', title: 'Build UI', desc: 'Accessible, responsive front-end implementation.' },
      { step: '04', title: 'Iterate', desc: 'Measure, refine, and optimize conversion.' },
    ],
    technologies: ['Figma', 'Storybook', 'React', 'Tailwind', 'Framer Motion'],
    features: ['User research', 'Wireframes & prototyping', 'Design systems', 'Accessibility (WCAG)', 'Responsive UI', 'Motion & micro-interactions'],
    benefits: [
      { title: 'Consistent', desc: 'One system across every screen.', icon: '🧠' },
      { title: 'Faster dev', desc: 'Reusable components reduce rework.', icon: '⏱️' },
      { title: 'Higher conversion', desc: 'UX designed to drive outcomes.', icon: '📊' },
    ],
    techSubtitle: 'Design tooling we use to craft systems, prototypes, and production-ready assets.',
    techPanels: [
      { title: 'Design Tools', slugs: ['figma', 'adobe-xd', 'sketch', 'photoshop', 'canva', 'adobe-illustrator', 'adobe-creative-cloud'] },
    ],
  },
  {
    id: 5,
    slug: 'e-commerce-development',
    title: 'E-commerce Development',
    tag: 'Engineering',
    shortDescription: 'Shopify, WooCommerce, or custom storefronts — optimized for speed and conversions.',
    navDescription: 'Storefronts & checkout flows that convert.',
    fullDescription:
      'We build e-commerce experiences that convert: fast storefronts, clean checkout flows, and reliable integrations. Whether you need Shopify customization or a custom commerce build, we deliver with premium polish.',
    icon: 'ShoppingCart',
    accent: '#C0392B',
    bg: '#FDF0EE',
    illustration: 'ecommerce',
    process: [
      { step: '01', title: 'Store strategy', desc: 'Catalog, checkout, and integration planning.' },
      { step: '02', title: 'UX & UI', desc: 'Product discovery and purchase flow refinement.' },
      { step: '03', title: 'Build', desc: 'Theme/custom build, payments, and automation.' },
      { step: '04', title: 'Optimize', desc: 'Performance, SEO, and A/B experimentation.' },
    ],
    technologies: ['Shopify', 'WooCommerce', 'Stripe', 'Algolia', 'React'],
    features: ['Storefront builds', 'Checkout optimization', 'Payment integrations', 'SEO-ready pages', 'Product search', 'Analytics & tracking'],
    benefits: [
      { title: 'Higher AOV', desc: 'Better discovery and upsell flows.', icon: '🛒' },
      { title: 'Faster loads', desc: 'Speed improvements that lift conversion.', icon: '⚡' },
      { title: 'Reliable ops', desc: 'Stable integrations and clean data.', icon: '✅' },
    ],
    techSubtitle: 'Commerce platforms we use to build fast storefronts and reliable checkout flows.',
    techPanels: [
      { title: 'E-commerce Stack', slugs: ['shopify', 'woocommerce', 'magento', 'bigcommerce', 'prestashop', 'opencart', 'nopcommerce'] },
    ],
  },
  {
    id: 6,
    slug: 'cms-development',
    title: 'CMS Development',
    tag: 'Engineering',
    shortDescription: 'WordPress and headless CMS builds that make publishing simple and fast.',
    navDescription: 'Editor-friendly CMS & headless builds.',
    fullDescription:
      'We create content systems that editors love: structured content, fast pages, and clean workflows. From WordPress to headless stacks, we ship CMS solutions that scale.',
    icon: 'LayoutGrid',
    accent: '#2E6E9E',
    bg: '#F0F5FA',
    illustration: 'cms',
    process: [
      { step: '01', title: 'Content model', desc: 'Define content types, fields, and workflows.' },
      { step: '02', title: 'Build CMS', desc: 'Theme or headless setup with best practices.' },
      { step: '03', title: 'Integrate', desc: 'Search, forms, auth, and 3rd-party services.' },
      { step: '04', title: 'Train', desc: 'Editor training and documentation.' },
    ],
    technologies: ['WordPress', 'Sanity', 'Contentful', 'Next.js', 'Vite'],
    features: ['WordPress builds', 'Headless CMS', 'Content migrations', 'SEO & performance', 'Role-based editing', 'Reusable page blocks'],
    benefits: [
      { title: 'Editor-friendly', desc: 'Publishing without headaches.', icon: '📝' },
      { title: 'Scalable content', desc: 'Structured content that grows.', icon: '🗂️' },
      { title: 'Fast sites', desc: 'Performance as a first-class feature.', icon: '🚀' },
    ],
    techSubtitle: 'CMS platforms and builders we use to ship editor-friendly systems.',
    techPanels: [
      { title: 'CMS Stack', slugs: ['wordpress', 'joomla', 'wix', 'webflow', 'squarespace', 'elementor', 'wpbakery', 'brizy'] },
    ],
  },
  {
    id: 7,
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    tag: 'Growth',
    shortDescription: 'SEO, content, and performance campaigns designed to drive measurable growth.',
    navDescription: 'SEO, content & performance campaigns.',
    fullDescription:
      'We help teams grow with modern digital marketing: SEO foundations, content strategy, and performance campaigns. Everything is measured, iterated, and aligned to business outcomes.',
    icon: 'Megaphone',
    accent: '#C96A2E',
    bg: '#FFF3E8',
    illustration: 'marketing',
    process: [
      { step: '01', title: 'Audit', desc: 'SEO + analytics review and opportunity mapping.' },
      { step: '02', title: 'Plan', desc: 'Content and channel strategy with milestones.' },
      { step: '03', title: 'Execute', desc: 'Campaign setup, tracking, and creative iteration.' },
      { step: '04', title: 'Optimize', desc: 'Testing, reporting, and continuous improvements.' },
    ],
    technologies: ['GA4', 'Search Console', 'Ahrefs', 'HubSpot', 'Meta Ads'],
    features: ['SEO strategy', 'Content planning', 'Landing pages', 'Conversion tracking', 'Performance campaigns', 'Reporting dashboards'],
    benefits: [
      { title: 'More traffic', desc: 'Improve discoverability and demand.', icon: '📣' },
      { title: 'Better leads', desc: 'Targeted messaging and conversion paths.', icon: '🎯' },
      { title: 'Measurable ROI', desc: 'Clear reporting tied to outcomes.', icon: '📈' },
    ],
    techSubtitle: 'Growth platforms and channels we use to drive measurable outcomes.',
    techPanels: [
      { title: 'Marketing Stack', slugs: ['google-ads', 'seo', 'facebook-ads', 'linkedin-ads', 'youtube-ads', 'pinterest-ads', 'mailchimp', 'snapchat-ads', 'instagram-ads', 'x'] },
    ],
  },
];